# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string

menu: 
  - name: Projetos 
    submenu:
      - name: Em Desenvolvimento
      submenu:
        - name: Material de FÃ­sica
        link: /projects/mfisica
       - name: Finalizados
        link: /projects/ourlegacy
  - name: Posts
    link: /
 # - name: Projetos Finalizados
 #   link: /project
  - name: Sobre
    link: /about
  # - name: Follow me
  #  submenu:
   #   - name: GitHub
    #    icon: github
     #   link: http://github.com/alainpham
      # - name: LinkedIn
       # icon: linkedin-square
        # link: http://www.linkedin.com/in/alainpham
      #- name: Twitter
       # icon: twitter
        # link: https://twitter.com/koint
    
